export const BOOKING_LABELS = {
  en: {
    heading: 'Book a Free Consultation',
    subtext: 'Wednesday–Friday, 14:00–17:00 CET. 30-minute call.',
    name: 'Name',
    email: 'Email',
    contactMethod: 'Preferred Contact',
    description: 'What would you like to discuss?',
    submit: 'Book Consultation',
    sending: 'Booking...',
    successTitle: 'Booking Confirmed!',
    successText: 'Check your email for confirmation and calendar invite.',
    downloadIcs: 'Add to Calendar',
    error: 'Something went wrong. Please try again.',
    slotTaken: 'This slot is no longer available. Please pick another.',
    loading: 'Loading available times...',
    methods: { email: 'Email', whatsapp: 'WhatsApp', phone: 'Phone' },
  },
  hr: {
    heading: 'Rezervirajte besplatnu konzultaciju',
    subtext: 'Srijeda–petak, 14:00–17:00. Poziv od 30 minuta.',
    name: 'Ime',
    email: 'Email',
    contactMethod: 'Preferirani kontakt',
    description: 'O čemu biste htjeli razgovarati?',
    submit: 'Rezerviraj',
    sending: 'Rezerviram...',
    successTitle: 'Rezervacija potvrđena!',
    successText: 'Provjerite email za potvrdu i pozivnicu za kalendar.',
    downloadIcs: 'Dodaj u kalendar',
    error: 'Nešto je pošlo po krivu. Pokušajte ponovno.',
    slotTaken: 'Ovaj termin više nije dostupan. Odaberite drugi.',
    loading: 'Učitavanje dostupnih termina...',
    methods: { email: 'Email', whatsapp: 'WhatsApp', phone: 'Telefon' },
  },
  de: {
    heading: 'Buchen Sie eine kostenlose Beratung',
    subtext: 'Mittwoch–Freitag, 14:00–17:00 MEZ. 30-Minuten-Gespräch.',
    name: 'Name',
    email: 'E-Mail',
    contactMethod: 'Bevorzugter Kontakt',
    description: 'Worüber möchten Sie sprechen?',
    submit: 'Beratung buchen',
    sending: 'Wird gebucht...',
    successTitle: 'Buchung bestätigt!',
    successText: 'Prüfen Sie Ihre E-Mail für die Bestätigung und Kalendereinladung.',
    downloadIcs: 'Zum Kalender hinzufügen',
    error: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    slotTaken: 'Dieser Termin ist nicht mehr verfügbar. Bitte wählen Sie einen anderen.',
    loading: 'Verfügbare Zeiten werden geladen...',
    methods: { email: 'E-Mail', whatsapp: 'WhatsApp', phone: 'Telefon' },
  },
} as const

export type BookingLabels = (typeof BOOKING_LABELS)[keyof typeof BOOKING_LABELS]
