/**
 * Generate blog redirects from English slugs to Croatian directory slugs.
 * Also generates DE slug redirects.
 *
 * Blog posts live at /blog/{croatian-slug}/ in the URL structure.
 * English and German slugs in frontmatter need 308 redirects to the canonical URL.
 *
 * Usage: npx tsx scripts/generate-blog-redirects.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'

const BLOG_DIR = path.join(process.cwd(), 'content', 'blog')
const OUTPUT_PATH = path.join(process.cwd(), 'src', 'lib', 'blog-redirects.ts')

type RedirectEntry = {
  source: string
  destination: string
  permanent: boolean
}

function main(): void {
  const redirects: RedirectEntry[] = []
  const postDirs = fs.readdirSync(BLOG_DIR).filter((d) =>
    fs.statSync(path.join(BLOG_DIR, d)).isDirectory(),
  )

  for (const dirSlug of postDirs) {
    const enPath = path.join(BLOG_DIR, dirSlug, 'en.md')
    if (!fs.existsSync(enPath)) continue

    const raw = fs.readFileSync(enPath, 'utf-8')
    const { data } = matter(raw) as { data: {
      slug?: string
      translations?: Record<string, string>
    } }

    const enSlug = data.slug
    const deSlug = data.translations?.de

    // English slug → Croatian directory slug
    if (enSlug && enSlug !== dirSlug) {
      redirects.push({
        source: `/blog/${enSlug}/`,
        destination: `/blog/${dirSlug}/`,
        permanent: true,
      })
      // Also redirect without trailing slash
      redirects.push({
        source: `/blog/${enSlug}`,
        destination: `/blog/${dirSlug}/`,
        permanent: true,
      })
    }

    // German slug → Croatian directory slug (for /de/ prefix)
    if (deSlug && deSlug !== dirSlug) {
      redirects.push({
        source: `/de/blog/${deSlug}/`,
        destination: `/de/blog/${dirSlug}/`,
        permanent: true,
      })
      redirects.push({
        source: `/de/blog/${deSlug}`,
        destination: `/de/blog/${dirSlug}/`,
        permanent: true,
      })
    }
  }

  // Generate TypeScript output
  const output = `/**
 * Auto-generated blog slug redirects.
 * English and German slugs redirect to canonical Croatian directory slugs.
 *
 * Generated by: npx tsx scripts/generate-blog-redirects.ts
 * Total: ${redirects.length} redirects from ${postDirs.length} posts
 */

type BlogRedirect = {
  source: string
  destination: string
  permanent: boolean
}

const BLOG_REDIRECTS: BlogRedirect[] = ${JSON.stringify(redirects, null, 2)}

export { BLOG_REDIRECTS }
`

  fs.writeFileSync(OUTPUT_PATH, output)
  console.log(`[Redirects] Generated ${redirects.length} blog redirects from ${postDirs.length} posts`)
  console.log(`[Redirects] Output: ${OUTPUT_PATH}`)
}

main()
